### ISSUE TITLE
Doesn't work on Windows 11

### ISSUE THREAD

**Issue by mbcrump** [koolaidxk1d/Hotswap#3]
Can't get it to run on Windows 11.

**Comment by koolaidxk1d** [comment]
> Can't get it to run on Windows 11. 

Hi, Mike. I like your videos.

Did you download the release or build it?

What happens when you try to run it? 

What Win 11 build are you running?

**Comment by mbcrump** [comment]
Downloaded the release. 
Nothing happens, no visual indicators. It also isn't in Task Manager when I look for it. 
Windows 11 Home 22H2

**Comment by koolaidxk1d** [comment]
> Downloaded the release. 
> 
> Nothing happens, no visual indicators. It also isn't in Task Manager when I look for it. 
> 
> Windows 11 Home 22H2

I'm not sure why that would be. There was some issues on *some* machines with defender flagging it, so maybe pardon it in defender or try building it using the instructions.

**Comment by koolaidxk1d** [comment]
> Downloaded the release. 
> 
> Nothing happens, no visual indicators. It also isn't in Task Manager when I look for it. 
> 
> Windows 11 Home 22H2

https://dotnet.microsoft.com/download/dotnet-framework/net481

You might need to install this. Let me know if it works for you that way I can update the release to include it for future users.

**Comment by koolaidxk1d** [comment]
> Downloaded the release. Nothing happens, no visual indicators. It also isn't in Task Manager when I look for it. Windows 11 Home 22H2

Issue was related to some missing libraries in the release zip. The issue has been fixed and a new release has been put out. Thanks for pointing this out.
